server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email;sms
    stream:
      bindings:
        email-in-0:
          destination: send-communication
        sms-in-0:
          destination: send-communication
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
