spring:
  application:
    name: "shipment-order-service"

  cloud:
    stream:
      bindings:
        email-out-0:
          destination: send-communication
          content-type: application/json

  datasource:
    url: jdbc:mysql://localhost:3306/logistic
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"


server:
  port: 8081
